name: CI - Time Series Stock Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nbconvert jupyter

    - name: Run all notebooks
      run: |
        set -e  # stop if any command fails
        find Notebooks -name "*.ipynb" -type f | while read nb; do
          echo "🚀 Running $nb"
          jupyter nbconvert \
            --to notebook \
            --execute "$nb" \
            --output "executed_${nb##*/}" \
            --ExecutePreprocessor.timeout=600
        done
